import type { BusinessType, ProjectStage, ProjectType, SiteStatus } from './types';

export type WorkspaceBusinessConfig = {
  type: BusinessType;
  label: string;
  workspaceSubtitle: string;
  customerLabel: string;
  customerPlural: string;
  workLabel: string;
  workPlural: string;
  titleLabel: string;
  locationLabel: string;
  statusLabel: string;
  primaryMetricLabel: string;
  secondaryMetricLabel: string;
  tertiaryMetricLabel: string;
  quaternaryMetricLabel: string;
  teamIntro: string;
  inventoryIntro: string;
  billingIntro: string;
  crmIntro: string;
  overviewIntro: string;
  operationsIntro: string;
  ownerLabel: string;
  specialistLabel: string;
  fieldLeadLabel: string;
  touchpointLabel: string;
  stageLabels: Record<ProjectStage, string>;
  siteStatusLabels: Record<SiteStatus, string>;
  projectTypeLabels: Record<ProjectType, string>;
  aiSuggestions: { id: string; name: string; description: string; category: string }[];
};

const generalStageLabels: Record<ProjectStage, string> = {
  inquiry: 'New lead',
  consultation: 'Requirement review',
  design_in_progress: 'Offer being prepared',
  render_shared: 'Proposal shared',
  customer_approved: 'Approved to proceed',
  execution_started: 'Work in progress',
  completed: 'Completed',
  on_hold: 'On hold',
};

const configs: Record<BusinessType, WorkspaceBusinessConfig> = {
  general_business: {
    type: 'general_business',
    label: 'General business',
    workspaceSubtitle: 'Adaptive operations workspace for growing businesses.',
    customerLabel: 'Account',
    customerPlural: 'Accounts',
    workLabel: 'Work item',
    workPlural: 'Work items',
    titleLabel: 'Work title',
    locationLabel: 'Location / branch',
    statusLabel: 'Workflow status',
    primaryMetricLabel: 'Active accounts',
    secondaryMetricLabel: 'Open work items',
    tertiaryMetricLabel: 'Completed this cycle',
    quaternaryMetricLabel: 'Pending tasks',
    teamIntro: 'Keep ownership clear, balance workloads, and assign the right people across operations.',
    inventoryIntro: 'Track stock, purchase pressure, storage, and supplier dependencies in one workspace.',
    billingIntro: 'Track incoming revenue, outgoing expenses, cash position, and payable priorities.',
    crmIntro: 'Follow up faster, log conversations, and move each opportunity through a visible pipeline.',
    overviewIntro: 'A live control room for your calendar, follow-ups, business signals, and next actions.',
    operationsIntro: 'A shared execution board for tasks, finance pressure, stock alerts, and workflow attention.',
    ownerLabel: 'Account owner',
    specialistLabel: 'Specialist lead',
    fieldLeadLabel: 'Execution lead',
    touchpointLabel: 'Touchpoint',
    stageLabels: generalStageLabels,
    siteStatusLabels: {
      under_construction: 'Queued',
      ready: 'Ready',
      in_progress: 'Active',
    },
    projectTypeLabels: {
      living_room: 'New customer need',
      bedroom: 'Repeat business',
      office: 'B2B opportunity',
      full_home: 'Large engagement',
      kitchen: 'Service issue',
      retail: 'Retail / counter sale',
    },
    aiSuggestions: [
      { id: 'quote-drafter', name: 'Quote Drafter', description: 'Create faster quotes and estimate drafts from customer requirements.', category: 'Sales' },
      { id: 'followup-copilot', name: 'Follow-up Copilot', description: 'Generate WhatsApp and email follow-ups based on CRM history.', category: 'CRM' },
      { id: 'stock-forecast', name: 'Stock Forecast', description: 'Predict demand pressure and reorder windows from sales patterns.', category: 'Inventory' },
      { id: 'ops-summary', name: 'Operations Summary', description: 'Turn daily activity into a quick owner-ready business brief.', category: 'Operations' },
    ],
  },
  interior_decorator: {
    type: 'interior_decorator',
    label: 'Interior decorator',
    workspaceSubtitle: 'Studio operations, projects, billing, materials, and AI-assisted delivery.',
    customerLabel: 'Client',
    customerPlural: 'Clients',
    workLabel: 'Project',
    workPlural: 'Projects',
    titleLabel: 'Project title',
    locationLabel: 'Site location',
    statusLabel: 'Site status',
    primaryMetricLabel: 'Active clients',
    secondaryMetricLabel: 'Live projects',
    tertiaryMetricLabel: 'Completed installs',
    quaternaryMetricLabel: 'Pending tasks',
    teamIntro: 'Keep project ownership clear, balance studio workloads, and align site execution with design delivery.',
    inventoryIntro: 'Track materials, issued stock, purchase needs, and site-linked inventory in one place.',
    billingIntro: 'Track quotations, material costs, labour, stage-based billing, and receivables.',
    crmIntro: 'Manage client follow-ups, design approvals, and sales momentum without losing project context.',
    overviewIntro: 'A studio control room for calendar, approvals, follow-ups, and project delivery signals.',
    operationsIntro: 'Track studio execution, task deadlines, purchase pressure, and client commitments from one board.',
    ownerLabel: 'Project owner',
    specialistLabel: 'Design lead',
    fieldLeadLabel: 'Site lead',
    touchpointLabel: 'Client touchpoint',
    stageLabels: {
      inquiry: 'Inquiry received',
      consultation: 'Consultation done',
      design_in_progress: 'Design in progress',
      render_shared: 'Preview shared',
      customer_approved: 'Approved to execute',
      execution_started: 'Execution started',
      completed: 'Completed',
      on_hold: 'On hold',
    },
    siteStatusLabels: {
      under_construction: 'Under construction',
      ready: 'Ready',
      in_progress: 'In progress',
    },
    projectTypeLabels: {
      living_room: 'Living room',
      bedroom: 'Bedroom',
      office: 'Office',
      full_home: 'Full home',
      kitchen: 'Kitchen',
      retail: 'Retail space',
    },
    aiSuggestions: [
      { id: 'room-preview', name: 'Room Preview AI', description: 'Create visual previews for client approvals and faster design selling.', category: 'Design' },
      { id: 'material-planner', name: 'Material Planner', description: 'Estimate material requirements and likely purchase pressure.', category: 'Procurement' },
      { id: 'site-followup', name: 'Site Follow-up Writer', description: 'Turn site notes into client-ready updates and reminders.', category: 'CRM' },
      { id: 'quote-assistant', name: 'Interior Quote Assistant', description: 'Draft quotations from room scope, budget, and materials.', category: 'Sales' },
    ],
  },
  shoe_shop: {
    type: 'shoe_shop',
    label: 'Shoe shop',
    workspaceSubtitle: 'Retail-ready workspace for buyers, stock, sales flow, and repeat business.',
    customerLabel: 'Buyer',
    customerPlural: 'Buyers',
    workLabel: 'Order',
    workPlural: 'Orders',
    titleLabel: 'Order / requirement title',
    locationLabel: 'Store / area',
    statusLabel: 'Fulfillment status',
    primaryMetricLabel: 'Active buyers',
    secondaryMetricLabel: 'Open orders',
    tertiaryMetricLabel: 'Delivered orders',
    quaternaryMetricLabel: 'Pending tasks',
    teamIntro: 'Coordinate store staff, sales ownership, stock attention, and customer handling from one roster.',
    inventoryIntro: 'Track fast-moving inventory, sizes, supplier restock pressure, and branch-ready stock visibility.',
    billingIntro: 'Track collections, vendor bills, operating expenses, and cash movement across the shop.',
    crmIntro: 'Manage repeat buyers, pending orders, follow-ups, and local selling opportunities from one queue.',
    overviewIntro: 'A retail control room for today’s orders, follow-ups, stock signals, and store priorities.',
    operationsIntro: 'Watch order handling, low-stock pressure, dues, and team tasks without bouncing between tools.',
    ownerLabel: 'Sales owner',
    specialistLabel: 'Category lead',
    fieldLeadLabel: 'Fulfillment lead',
    touchpointLabel: 'Buyer touchpoint',
    stageLabels: {
      inquiry: 'Buyer enquiry',
      consultation: 'Need understood',
      design_in_progress: 'Offer being prepared',
      render_shared: 'Quote shared',
      customer_approved: 'Order confirmed',
      execution_started: 'Fulfillment started',
      completed: 'Delivered',
      on_hold: 'Waiting',
    },
    siteStatusLabels: {
      under_construction: 'Reorder needed',
      ready: 'Ready to sell',
      in_progress: 'Being fulfilled',
    },
    projectTypeLabels: {
      living_room: 'Walk-in sale',
      bedroom: 'Repeat purchase',
      office: 'Bulk order',
      full_home: 'Seasonal campaign',
      kitchen: 'Supplier issue',
      retail: 'Custom order',
    },
    aiSuggestions: [
      { id: 'catalog-helper', name: 'Catalog Helper', description: 'Recommend matching products and upsell combinations for buyers.', category: 'Sales' },
      { id: 'size-demand', name: 'Size Demand Forecast', description: 'Forecast fast-moving sizes and styles before you stock out.', category: 'Inventory' },
      { id: 'repeat-buyer', name: 'Repeat Buyer Nudges', description: 'Create personalized follow-up messages for recent or seasonal buyers.', category: 'CRM' },
      { id: 'vendor-brief', name: 'Vendor Order Brief', description: 'Convert low-stock signals into a clean supplier purchase brief.', category: 'Procurement' },
    ],
  },
  sports_shop: {
    type: 'sports_shop',
    label: 'Sports shop',
    workspaceSubtitle: 'Manage products, buyer demand, teams, and seasonal stock with one adaptive workspace.',
    customerLabel: 'Buyer',
    customerPlural: 'Buyers',
    workLabel: 'Order',
    workPlural: 'Orders',
    titleLabel: 'Order / requirement title',
    locationLabel: 'Store / area',
    statusLabel: 'Fulfillment status',
    primaryMetricLabel: 'Active buyers',
    secondaryMetricLabel: 'Open orders',
    tertiaryMetricLabel: 'Delivered orders',
    quaternaryMetricLabel: 'Pending tasks',
    teamIntro: 'Keep store teams aligned around buyers, stock movement, and event-driven selling periods.',
    inventoryIntro: 'Track product movement, supplier pressure, seasonal demand, and slow-moving stock clearly.',
    billingIntro: 'Track sales inflow, supplier payouts, operating expenses, and cash visibility in one page.',
    crmIntro: 'Manage buyer follow-ups, team or academy accounts, and recurring demand from one queue.',
    overviewIntro: 'A sports retail control room for orders, stock pressure, selling priorities, and follow-ups.',
    operationsIntro: 'Stay ahead of seasonal demand, pending collections, and stock movement from one board.',
    ownerLabel: 'Sales owner',
    specialistLabel: 'Category lead',
    fieldLeadLabel: 'Fulfillment lead',
    touchpointLabel: 'Buyer touchpoint',
    stageLabels: {
      inquiry: 'Buyer enquiry',
      consultation: 'Requirement mapped',
      design_in_progress: 'Offer being prepared',
      render_shared: 'Quote shared',
      customer_approved: 'Order confirmed',
      execution_started: 'Fulfillment started',
      completed: 'Delivered',
      on_hold: 'Waiting',
    },
    siteStatusLabels: {
      under_construction: 'Restock needed',
      ready: 'Ready to sell',
      in_progress: 'Being fulfilled',
    },
    projectTypeLabels: {
      living_room: 'Walk-in sale',
      bedroom: 'Repeat purchase',
      office: 'Team order',
      full_home: 'Seasonal campaign',
      kitchen: 'Tournament supply',
      retail: 'Custom order',
    },
    aiSuggestions: [
      { id: 'seasonal-demand', name: 'Seasonal Demand AI', description: 'Project category demand around tournaments, school seasons, and local trends.', category: 'Inventory' },
      { id: 'bundle-maker', name: 'Bundle Maker', description: 'Suggest bundles for sports categories, accessories, and upsells.', category: 'Sales' },
      { id: 'academy-followup', name: 'Academy Follow-up Writer', description: 'Draft outreach for schools, academies, and recurring bulk buyers.', category: 'CRM' },
      { id: 'purchase-brief', name: 'Purchase Brief Builder', description: 'Turn reorder signals into a clean supplier request.', category: 'Procurement' },
    ],
  },
  retail_store: {
    type: 'retail_store',
    label: 'Retail store',
    workspaceSubtitle: 'One dashboard for buyers, orders, stock, billing, and everyday retail operations.',
    customerLabel: 'Buyer',
    customerPlural: 'Buyers',
    workLabel: 'Order',
    workPlural: 'Orders',
    titleLabel: 'Order / request title',
    locationLabel: 'Branch / area',
    statusLabel: 'Fulfillment status',
    primaryMetricLabel: 'Active buyers',
    secondaryMetricLabel: 'Open orders',
    tertiaryMetricLabel: 'Delivered orders',
    quaternaryMetricLabel: 'Pending tasks',
    teamIntro: 'Run front-of-store, fulfillment, stock, and customer handling from one operating layer.',
    inventoryIntro: 'Track catalog movement, low-stock alerts, supplier pressure, and stock value with clarity.',
    billingIntro: 'Monitor collections, expenses, dues, and cash position across everyday retail operations.',
    crmIntro: 'Follow up with buyers, manage repeat business, and keep order commitments visible.',
    overviewIntro: 'A retail control room for buyers, stock signals, billing pressure, and next actions.',
    operationsIntro: 'Track store operations, task pressure, vendor dependencies, and execution in one board.',
    ownerLabel: 'Sales owner',
    specialistLabel: 'Category lead',
    fieldLeadLabel: 'Fulfillment lead',
    touchpointLabel: 'Buyer touchpoint',
    stageLabels: {
      inquiry: 'Buyer enquiry',
      consultation: 'Need mapped',
      design_in_progress: 'Offer being prepared',
      render_shared: 'Quote shared',
      customer_approved: 'Order confirmed',
      execution_started: 'Fulfillment started',
      completed: 'Delivered',
      on_hold: 'Waiting',
    },
    siteStatusLabels: {
      under_construction: 'Reorder needed',
      ready: 'Ready to sell',
      in_progress: 'Being fulfilled',
    },
    projectTypeLabels: {
      living_room: 'Walk-in sale',
      bedroom: 'Repeat purchase',
      office: 'Bulk order',
      full_home: 'Campaign order',
      kitchen: 'Supplier issue',
      retail: 'Custom order',
    },
    aiSuggestions: [
      { id: 'basket-builder', name: 'Basket Builder', description: 'Suggest cross-sells and bundles from buyer context.', category: 'Sales' },
      { id: 'restock-alert', name: 'Restock Intelligence', description: 'Spot fast-moving SKUs and overdue purchases earlier.', category: 'Inventory' },
      { id: 'buyer-message', name: 'Buyer Message AI', description: 'Draft promotions and repeat-buyer follow-ups quickly.', category: 'CRM' },
      { id: 'cash-summary', name: 'Cash Summary', description: 'Summarize revenue and spend signals for the owner each day.', category: 'Finance' },
    ],
  },
  service_business: {
    type: 'service_business',
    label: 'Service business',
    workspaceSubtitle: 'Manage enquiries, service jobs, teams, collections, and recurring follow-ups in one place.',
    customerLabel: 'Client',
    customerPlural: 'Clients',
    workLabel: 'Job',
    workPlural: 'Jobs',
    titleLabel: 'Job / requirement title',
    locationLabel: 'Service area',
    statusLabel: 'Service status',
    primaryMetricLabel: 'Active clients',
    secondaryMetricLabel: 'Open jobs',
    tertiaryMetricLabel: 'Closed jobs',
    quaternaryMetricLabel: 'Pending tasks',
    teamIntro: 'Coordinate field teams, job ownership, and follow-ups from one shared control room.',
    inventoryIntro: 'Track service stock, tools, replacement parts, and vendor pressure in one page.',
    billingIntro: 'Track collections, service invoices, expenses, and cash movement across jobs.',
    crmIntro: 'Stay on top of client conversations, renewals, service reminders, and escalation handling.',
    overviewIntro: 'A service control room for calendar jobs, follow-ups, dues, and execution signals.',
    operationsIntro: 'Stay ahead of service workload, unpaid jobs, and task pressure with one board.',
    ownerLabel: 'Account owner',
    specialistLabel: 'Service lead',
    fieldLeadLabel: 'Field lead',
    touchpointLabel: 'Service touchpoint',
    stageLabels: {
      inquiry: 'New enquiry',
      consultation: 'Requirement review',
      design_in_progress: 'Scope being prepared',
      render_shared: 'Estimate shared',
      customer_approved: 'Approved to serve',
      execution_started: 'Service in progress',
      completed: 'Closed',
      on_hold: 'On hold',
    },
    siteStatusLabels: {
      under_construction: 'Waiting',
      ready: 'Ready',
      in_progress: 'On service',
    },
    projectTypeLabels: {
      living_room: 'New service need',
      bedroom: 'Repeat service',
      office: 'Business client',
      full_home: 'Large contract',
      kitchen: 'Emergency issue',
      retail: 'On-site request',
    },
    aiSuggestions: [
      { id: 'job-summary', name: 'Job Summary AI', description: 'Turn service notes into a clean summary for clients and teams.', category: 'Operations' },
      { id: 'estimate-helper', name: 'Estimate Helper', description: 'Draft faster service estimates from issue details.', category: 'Sales' },
      { id: 'reminder-writer', name: 'Reminder Writer', description: 'Create reminders for renewals, collections, and revisit dates.', category: 'CRM' },
      { id: 'parts-forecast', name: 'Parts Forecast', description: 'Predict common part demand and likely restock pressure.', category: 'Inventory' },
    ],
  },
};

export const getBusinessConfig = (type: BusinessType): WorkspaceBusinessConfig =>
  configs[type] ?? configs.general_business;
